downTableVideo:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-downTableVideo
  events:
    - http:
        path: api/v1/videos/down
        method: POST
        cors: true

getSignedUrl:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getSignedUrl
  events:
    - http:
        path: api/v1/videos/sign
        method: GET
        cors: true

getVideoByUuid:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getVideoByUuid
  events:
    - http:
        path: api/v1/videos/{uuid}
        method: GET
        cors: true

getVideos:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-getVideos
  events:
    - http:
        path: api/v1/videos
        method: GET
        cors: true

upTableVideo:
  handler: src/app.handler
  name: ${self:service}-${self:provider.stage}-upTableVideo
  events:
    - http:
        path: api/v1/videos/up
        method: POST
        cors: true
